### ISSUE TITLE
Velge engelsk navn på drift

### ISSUE THREAD

**Issue by felixalbrigtsen** [Programvareverkstedet/Drift#26]
Halvårsmøte/2022V ble holdt på engelsk, og drift ble omtalt som ![drift](https://m.media-amazon.com/images/M/MV5BMTQ2NTMxODEyNV5BMl5BanBnXkFtZTcwMDgxMjA0MQ@@._V1_.jpg)

Technical dept, computer maintenance, IT, the wizards, noe annet?

**Comment by adrlau** [comment]
Wizards er skikkelig kult, men ikke en oversettelse av drift.  Operasjons elns er vel en mer korrekt oversettelse av drift.

**Comment by dali99** [comment]
I dont even mind being a drifter, seems like pretty accurate description of the manuevers we have to pull off

**Comment by h7x4** [comment]
We drift off from our initial goals and plans every single meeting, checks out
