### ISSUE TITLE
Sette opp ny databaseserver

### ISSUE THREAD

**Issue by adrlau** [Programvareverkstedet/Drift#32]
knakeligbrak burde utfases, dermed bør det settes opp en ny databaseserver for å erstatte den.

**Comment by felixalbrigtsen** [comment]
https://www.pvv.ntnu.no/pvv/Maskiner/Bicep er på vei. Den *kjører* mariadb og postgres nå, men skal både flyttes og konfigureres litt til, forvent nedetid.

Vi burde planlegge en transition period, gradvis flytte over tjenester, før vi flytter over CNAMEs for mysql og postgres.
