### ISSUE TITLE
Move nettsiden@spikkjeposche to nettsiden@bekkalokk

### ISSUE THREAD

**Issue by dali99** [Programvareverkstedet/Drift#36]
[Programverkstedet/nettsiden](https://github.com/Programvareverkstedet/nettsiden) should be packaged for Nix use with php-fpm and nginx, and then moved to bekkalokk. It will need a new auth endpoint.

Remember to update the wiki!

Depends on #67

**Comment by h7x4** [comment]
Moved to bekkalokk
