### ISSUE TITLE
proxmox unifying 

### ISSUE THREAD

**Issue by adrlau** [Programvareverkstedet/Drift#57]
Dersom vi endrer opp med flere fungerende proxmox instanser er det en ide å legge nodene til i hverandre slik at en kan administrere og ha faktisk clustering.

**Comment by felixalbrigtsen** [comment]
This is impossible. Proxmox clusters are a myth, only Unicorns and Chuck norris can make them without failing.

**Comment by adrlau** [comment]
Isn't clusters a main feature of proxmox.
