### ISSUE TITLE
Sett inn mer RAM i bicep

### ISSUE THREAD

**Issue by h7x4** [Programvareverkstedet/Drift#60]
Stakkars bicep sitter med to sterke CPU-er og kun 12GB RAM, men den har sannsynligvis plass til noe sånt som 384GB toppen. Vi har en del DDR3 RAM liggende rundtom, kanskje noen kunne tatt en tur ned på serverrommet og satt inn litt mer?

Husk å oppdatere https://www.pvv.ntnu.no/pvv/Maskiner/Bicep!

**Comment by felixalbrigtsen** [comment]
`
felixalb@bicep:~/ > free -h
               total        used        free      shared  buff/cache   available
Mem:            47Gi       3.2Gi        15Gi       2.1Gi        28Gi        41Gi
Swap:             0B          0B          0B
`
