### ISSUE TITLE
Deprecate Essendrop

### ISSUE THREAD

**Issue by h7x4** [Programvareverkstedet/Drift#61]
[Essendrop](https://www.pvv.ntnu.no/pvv/Maskiner/Essendrop) is a VM on [Asgore](https://www.pvv.ntnu.no/pvv/Maskiner/Asgore) currently only hosts gogs, our git service.

Remember to update the wiki!

Depends on #62

**Comment by felixalbrigtsen** [comment]
Essendrop has been powered off for quite a while, and the gitea instance is getting good, so I believe this is done!
