### ISSUE TITLE
Move webmail@spikkjeposche to webmail@bekkalokk

### ISSUE THREAD

**Issue by h7x4** [Programvareverkstedet/Drift#68]
[Spikkjeposche](https://www.pvv.ntnu.no/pvv/Maskiner/Spikkjeposche) currently hosts 4 webmail sites. We should setup hosting for new webmail clients, to remove the ones at spikkjeposche. Currently, we're aiming to set up [Snappymail](https://snappymail.eu/) and [Roundcube](https://roundcube.net/), as these seem reasonably updated. Roundcube has an existing [NixOS module](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/mail/roundcube.nix), while Snappymail only has a [package, currently unstable](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/servers/snappymail/default.nix).

Remember to update the wiki!

**Comment by dali99** [comment]
Don't these webmail clients do some crazy local auth things? This might be blocked on a PAM module and login support for boxes.

This might also mean they shouldn't be on bekkalokk
