### ISSUE TITLE
Dørsensor mikrokontroller

### ISSUE THREAD

**Issue by dali99** [Programvareverkstedet/Drift#7]
I stedet for å bruke en hel pi til dørsensor, bytt til en mikrokontroller

**Comment by pbsds** [comment]
billige arduinoer som klarer å bruke WIFI har en tendens til å dø. Spør folk på omegaverkstedet om hvilke arduinoer som bør brukes

**Comment by felixalbrigtsen** [comment]
https://github.com/bjda made this issue redundant by configuring an IoT sensor with our HomeAssistant instance.
