### ISSUE TITLE
Deprecate Spikkjeposche

### ISSUE THREAD

**Issue by h7x4** [Programvareverkstedet/Drift#71]
[Spikkjeposche](https://www.pvv.ntnu.no/pvv/Maskiner/Spikkjeposche) currently hosts several webservices, like nettsiden, webmail clients, Mediawiki, and SimpleSAML. There are plans to update these, and move them to different machines. To assist with our plans of reducing the machine count before the serverroom purge, this machine should be deprecated.

Remember to update the wiki!

Depends on #69
Depends on #68
Depends on #67
Depends on #36

**Comment by pbsds** [comment]
;(

I hopy by favorite breakfast spread lives on in name in some capacity or another

**Comment by h7x4** [comment]
All spikkjeposche services moved to bekkalokk
