### ISSUE TITLE
Create a virtual replacement for hildring

### ISSUE THREAD

**Issue by h7x4** [Programvareverkstedet/Drift#73]
[Hildring](https://www.pvv.ntnu.no/pvv/Maskiner/Hildring) is currently acting as a login server, where a lot of people are running tmux and screen shells with stuff like IRC clients and mail readers. It is a small machine that can easily be replaced with a VM, and should probably be replaced to reduce the amount of machines for the serverroom purge.

It should (probably) (at least) have the following software installed:

- emacs
- mutt
- irssi
- tmux
- zsh
- tcsh
- telnet
- perl
- procmail
- vim
- python3

Please remember to update the wiki!

**Comment by adrlau** [comment]
Lol vm on asgore.

**Comment by h7x4** [comment]
pog
